### PR TITLE
Rename variables to reflect units for ekg metrics

### PR DESCRIPTION
**Pull request by awjchen**
This PR just renames two intermediate variables related to EKG metrics in order to reflect their units of measurement.

As a sanity check, both `dbConnAcquireLatency` and `poolConnAcquireLatency` have values of about `13500` for a local postgres instance on my machine.

### CODE REVIEW

**Review by evertedsphere — COMMENTED** [review]
looks good to me, thanks for fixing this :)

**Review by evertedsphere — APPROVED** [review]

**Comment by evertedsphere** [comment]
@awjchen do any documentation etc changes also need to be made upstream in graphql-engine or in your tagged metrics PR?

**Comment by awjchen** [comment]
@evertedsphere It looks like there's currently no documentation in graphql-engine (or my PR) about `dbConnAcquireLatency` and `poolConnAcquireLatency` and no dependence on their units of measure. In that case, since this PR makes no functional changes, we shouldn't need to make any changes upstream (other than adding docs :smile:)

**Comment by evertedsphere** [comment]
okay, that makes sense. i think if your PR also bumps the `pg-client-hs` version in the cabal.project file, it's worth adding this to the description or something so reviewers can give it a look-over as a sanity check, but otherwise everything should be fine. (docs is good!)

**Pull request merged**
