### PR TITLE
Allow resizing Postgres connection pools

### PR DESCRIPTION
**Pull request by abooij**
See hasura/graphql-engine-mono#4352 for context. Upstream PR: hasura/pool#8.

### CODE REVIEW

**Comment by abooij** [comment]
Maybe a simple upgrade is sufficient, and the new method isn't necessary.

**Review by rakeshkky — APPROVED** [review]
LGTM

**Comment by abooij** [comment]
Perhaps, as a cleaner alternative to the wrapper method introduced by this PR, we can export the constructor of `PGPool`, so that the underlying `Pool` can be accessed directly - this would allow us to do all the required resizing and trimming using the methods from the `pool` library.

**Comment by rakeshkky** [comment]
@abooij I'd prefer keeping the internals of resizing a Postgres pool within this package by neatly exposing `resizePGPool` abstraction. I believe, to resize a pool we need to
1. set the max resources `TVar` using `resizePool`
2. destroy the resources if we are downsizing the pool using `tryTrimPool` and when upsizing this function do nothing.

Please correct me if I'm wrong.

If you're okay, I'll merge this PR and update the `pg-client-hs` references in the graphql-engine.

**Comment by abooij** [comment]
Fine by me!

**Pull request merged**
